//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated by a tool InstallerGenerator.
//
//
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Zenject;
using Ecs.Game;
using Ecs.Common;

public static class GameInstaller {
	public static void Install(DiContainer container) {

		// 100000
		container.BindInterfacesAndSelfTo<PlayerInitializeSystem>().AsSingle();
		container.BindInterfacesAndSelfTo<PrefabsDatabase>().AsSingle();
	}
}