//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated by a tool InstallerGenerator.
//
//
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Zenject;
using Ecs.Shared;
using Ecs;

public static class ProjectInstaller {
	public static void Install(DiContainer container) {

		// 100000
		container.BindInterfacesAndSelfTo<LoadSceneController>().AsSingle();
		container.BindInterfacesAndSelfTo<ScenesDatabase>().AsSingle();
		container.BindInterfacesAndSelfTo<LoadLocationSystem>().AsSingle();

		// 500000
		container.BindInterfacesAndSelfTo<StartSceneLoader>().AsSingle().NonLazy();
	}
}